spring:
  main:
    web-application-type: reactive
  application:
    name: auth
  r2dbc:
    url: r2dbc:postgresql://158.247.250.91:5432/firststory
    username: postgres
    password: fst@3012
    pool:
      initial-size: 10
      max-size: 10
  redis:
    host: 158.247.250.91
    port: 6379
    lettuce:
      shutdown-timeout: 200ms
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://158.247.250.91:5432/firststory
    user: postgres
    password: fst@3012
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  webflux:
    static-path-pattern: /oauth2/**
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration